### ISSUE TITLE
[FEAT]: SRT Subtitles "\{{}\an8\" support

### ISSUE THREAD

**Issue by kralcak** [nova-video-player/aos-AVP#1365]
### Description

There are more and more .srt subtitles which are having "\{{}\an8\" prefix before text which should place this text at the top of the screen but Nova player does not support this. Vimu media player fixed this in version 10.8

**Comment by courville** [comment]
Already fixed in 6.3.16 GitHub release. Please test and report.

**Comment by kralcak** [comment]
I have found an issue with showing both top and bottom subtitle as on this picture from VLC 

![image](https://github.com/user-attachments/assets/88bcbb2b-7664-4085-b352-194fb95bde9d)

On TV in NOVA only top subtitle is shown and bottom is not visible.
I have uploaded part of the movie and subtitles here : 
https://mega.nz/file/aA11RDYB#63VYfzJaV7kzllycNjBDk0Sq-SgYFCwEV5K5Cwfy7gA
https://mega.nz/file/fUMFRZwJ#hk9fVDj6obgYzNy54BbJCP4CW__FClxi1AkT_jaoyh0

time around 1m11s

**Comment by courville** [comment]
Thanks for sharing the sample. I understand the issue: a top subtitle can have a longer display time than the bottom one and must stay active. This raises some complications but needs to be managed.

```
9
00:01:11,188 --> 00:01:37,197
{\an8}<i>KDO ŘÍKÁ, ŽE NA VELIKOSTI NEZÁLEŽÍ?</i>

10
00:01:18,061 --> 00:01:24,966
Někde jsem viděla video.
Byl na něm pár, který souložil
```

**Comment by tharsim** [comment]
I am using 6.3.17 on Android TV, still not showing subtitle on top despite the tag {\an8}.

**Comment by courville** [comment]
@tharsim, could you please provide sample? It works on my side in my particular case.

**Comment by tharsim** [comment]
@courville, I finally figured out what's happening with my subtitle positioning issue. When I use subtitles from a separate SRT file in the same folder as my video, the player correctly positions them at the top of the screen without any problem when using the {\an8} tag. But whenever I try to play videos with subtitles embedded inside the MKV container, they're not positioning to the top no matter what I do. I tested this extensively across different media players (Stremio, Vimu, and Nova), playing files from my external hard drive connected to my Android box. I tried both videos with embedded subtitles and videos with separate subtitle files, and the behavior is consistent every time.

**Comment by courville** [comment]
@tharsim, I can reproduce the issue when muxing a sub into an mkv. It turns out that the txt in the srt.srt external subtitle file being muxed looks like for instance
```
{\an6}<i>an 6 position text:\nis it working?</i>
```
But when muxed it shows like:
```
\{\\an6\}<i>an 6 position text:\nis it working?</i>
```
escaping my pattern detection somehow.
I manually muxed the sub into the mkv via ffmpeg and I am not sure it represents a real case.
Would you have a sample mkv with embedded subs with the {\an8} tags so that I check if my interpretation is correct?

**Comment by courville** [comment]
@tharsim I have mkv files with embedded subtitles and the proper formatting for the `{\anX}` tags that works with nova. 
I checked as well external subtitles. Please share a sample that positions subs on top with other players and not nova and I will probably find what I am doing wrong.

**Comment by tharsim** [comment]
@courville, I recorded [this video](https://store5.gofile.io/download/web/a001050c-ac25-4bbf-91c0-0c47dfc6e635/20250113_130316.mp4) showing a sample. Note: same file, same subtitle. I can give you other files as well.

**Comment by courville** [comment]
> [@courville](https://github.com/courville), I recorded [this video](https://store5.gofile.io/download/web/a001050c-ac25-4bbf-91c0-0c47dfc6e635/20250113_130316.mp4) showing a sample. Note: same file, same subtitle. I can give you other files as well.

thx for sharing. I will need the sample file to fix it. I am sure it is linked to a specific parsing that I need to adapt that does not work in this case. You can send me by email (software at courville dot org) reference to the video or sample extracted from the file with ffmpeg e.g.:
```
ffmpeg -i input.mkv -ss 00:04:39 -to 00:06:00 -map 0 -c copy output.mkv
```

**Comment by courville** [comment]
@tharsim, thanks for sharing the sample file. I found the issue, indeed in the file format is different `\{\\an8\}`.
I will add this in my parser instead of removing it.

**Comment by courville** [comment]
https://github.com/nova-video-player/aos-AVP/releases/tag/v6.3.19 released with the fix

**Comment by tharsim** [comment]
@courville, great. And a bunch of thanks! I have tested the new version and now the subtitles are showing on top for embedded subtitles as well.
