### ISSUE TITLE
[Bug]: Bluetooth Audio Sync

### ISSUE THREAD

**Issue by eng3** [nova-video-player/aos-AVP#1529]
### Problem description

Using Nvidia Shield.  Plex, Youtube, Nova are all fine connected to my speaker system (via hdmi)
When I connect to Nvidia Shield using my Bluetooth, Plex and Youtube are in sync.  Nova is delayed by around 250ms.
A workaround is to adjust the delay.  There is a global option but then I have to switch it back if i switch back to the speakers.

### Steps to reproduce the issue

1. Connect Bluetooth
2. Play video

### Expected behavior

Audio in sync

### Your phone/tablet/androidTV model

Nvidia Shield 2019 Pro

### Operating system version

Android 11

### Application version and app store

6.4.3 from Play Store

**Comment by courville** [comment]
Could you please try github release 6.4.11 since I think I recently fixed an issue related to AV system delay estimation and compensation.

**Comment by eng3** [comment]
When connected to my AV system, the sync has been working fine.  It is only when connected via bluetooth (bypassing AV system), where the sync is off (only with your app).  Is it still worthwhile to test 6.4.11?

**Comment by courville** [comment]
Could you please try out specifically this apk https://drive.google.com/file/d/1t-biiwXT669NQr6YRCaWwdUnEYTo6AF-/view?usp=sharing which uses AudioTrack.getLatency API instead of getOutputLatency which should provide better results with bluetooth.

**Comment by eng3** [comment]
It did not make a difference.  Is there a setting I need to enable?

**Comment by courville** [comment]
No setting, it should work. This means that getLatency does not provide the bluetooth codec additional latency.

**Comment by eng3** [comment]
ok, then it doesnt help.  BTW, another test, if I use the "another player" option, and select "Photos" app, videos play in sync.

**Comment by courville** [comment]
Can I ask what kind of BT headset you are using?

**Comment by eng3** [comment]
Sony WF-1000XM5

**Comment by eng3** [comment]
Any other questions or things to try?  I think the fact that there is no sync issue with other player apps (ie. "Photos") but not in nova player means it is an issue specific to nova player.

**Comment by courville** [comment]
The issue is that getDelay seems not to work for bluetooth and we need to implement a new timestamp based latency tracking in the code to be compatible with bluetooth headsets. I checked and vlc also suffers from the same issue. All players using ExoPlayer should be immune. When I get some time, I will implement the new scheme and share a build.

**Comment by courville** [comment]
Please check https://github.com/nova-video-player/aos-AVP/releases/tag/v6.4.16

**Comment by eng3** [comment]
hmm, I think its working.  If it is out of sync, I can't tell anymore.
The video even seems a little smoother but maybe that's my imagination.

**Comment by courville** [comment]
On the entirely rework audio pipeline infrastructure, I corrected some issues seen on some bluetooth headsets.

Can you please try this [arm64 apk](https://drive.google.com/open?id=15MMDGDV0s1VvQTesQNozSruA0-5pm49l) or [arm32 apk](https://drive.google.com/open?id=1eT-Ufua6vviyDAB2vVoj-9EJJUUtL1tz) depending of your architecture and report if it helps?

**Comment by courville** [comment]
I still get desync with this on shokz OpenRun Pro 2 headsets but not with sony WH-1000XM6... Audiotrak delay reported on openrun is huge and not on sony.
But I get the same desync on shokz than vlc now.
I will revert the two previous fixes since they are not helping.

**Comment by courville** [comment]
# Bluetooth A/V Sync Investigation Summary

## Scope

This investigation compared Bluetooth A/V sync behavior across:

- Nova with `android_sync=1`
- Nova with `android_sync=0`
- Nova with dynamic audio delay disabled
- VLC on the same device/headsets

The goal was to determine whether the observed desync was caused by Nova logic or by headset/Android route behavior.

## Main Result

The dominant variable is the Bluetooth route selected by Android for the headset, not a clean Nova-only regression.

Two headsets on the same phone behaved very differently:

- **Sony Bluetooth headset**
  - Audio delay around **60 ms**
  - AudioTrack minimum buffer size around **7,552 bytes**
  - Nova playback was in sync

- **Shokz / Aftershokz Bluetooth headset**
  - Audio delay around **680 to 682 ms**
  - AudioTrack minimum buffer size around **60,248 bytes**
  - Nova playback was audibly out of sync
  - VLC was also audibly out of sync on the same route

This indicates that the Shokz route is using a much deeper-latency Bluetooth audio path than the Sony route.

## Observed User-Visible Behavior

On the Shokz route:

- Audible A/V offset was typically in the **300 to 500 ms** range depending on test, mode, and content.
- The problem reproduced across:
  - `android_sync=1`
  - `android_sync=0`
  - dynamic delay disabled
- Reconnecting the headset did **not** reliably move it to a lower-latency route.
- Disabling the Android spatializer setting did **not** resolve the later failing runs.

On the Sony route:

- Playback remained acceptably in sync.
- Startup and steady-state audio delay stayed in the same low-latency range.

## Nova-Side Findings

### `android_sync=1`

`android_sync=1` was the most visibly sensitive to the high-latency Shokz route, especially during startup and warmup.

### `android_sync=0`

`android_sync=0` could look better in some earlier tests because it relied more heavily on static startup anchoring, but it was **not** a reliable solution once the route remained around **680 ms**.

### Dynamic Audio Delay Disabled

Disabling dynamic delay also did **not** solve the problem. With dynamic delay off, the route still remained badly out of sync on Shokz.

## Heuristics Tested

Several Nova-side heuristics were explored:

- bounded last-good delay holding for `android_sync=1`
- flooring warmup/playhead delay estimates toward static latency
- periodic `AudioTrack.getLatency()` refresh
- duplicate timestamp handling during AudioTrack warmup

These heuristics were **not kept** as product fixes because they were not robust across headsets:

- some changes helped one Bluetooth route
- the same changes worsened another Bluetooth route
- later evidence showed VLC was also affected on Shokz, weakening the case for a Nova-specific workaround

## Current Conclusion

Current evidence points to a **headset/route-dependent Android Bluetooth latency issue**, not a clean Nova-specific sync bug.

The strongest comparison is:

- **Sony**: low-latency route, small buffer, good sync
- **Shokz**: deep-latency route, large buffer, bad sync
- **VLC also affected on Shokz**

## Practical Product Direction

Given the current findings, the safest direction is:

1. Avoid keeping aggressive Nova heuristics that try to auto-correct one headset at the expense of others.
2. Treat the Shokz issue as primarily route/headset dependent.
3. Prefer a **manual Bluetooth audio offset** feature if user mitigation is needed.

## Short Issue Summary

- Same phone, same app, different Bluetooth headsets produce very different latency classes.
- Sony route is about **60 ms** with about **7.5 KB** AudioTrack min buffer and is in sync.
- Shokz route is about **680 ms** with about **60 KB** AudioTrack min buffer and is out of sync.
- VLC is also out of sync on Shokz.
- Experimental Nova sync heuristics were tested and discarded because they were not safe across devices.
- Current evidence favors an Android/headset route problem rather than a Nova-only regression.

**Comment by eng3** [comment]
I was using the Sony wf-1000xm5 earbuds and the new Dynamic Audio Delay option seemed to solve my issue.  Well, I've switch to Technics AZ-100 and the issue is back (with or without Dynamic Audio Delay.  I get approx 250ms delay.  90% of the time.  10% of the time it's actually in sync.
This is not the only app that this happens on.
What might be useful would be an option to set a global audio delay settings for bluetooth only.  (specific to device would be nice, but all bluetooth would be ok too).   My speakers have no sync issue so it is annoying switching back and forth.
