### ISSUE TITLE
[Bug]: audio out of sync after paused video is resumed

### ISSUE THREAD

**Issue by piter-pit** [nova-video-player/aos-AVP#1552]
### Problem description

I tested the newest version with AAC re-encoding to EAC3 and enabled Android frame timing as described. I noticed that audio goes out of sync when a paused video is resumed. This issue occurs regardless of the audio format—EAC3, AAC stereo, or AAC 5.1.

I remember a similar issue happened in the past, but I couldn’t find the previous report.

When Android frame timing is disabled, the video stutters. I also tried different settings like parser sync mode and automatic refresh rate, but the problem persists.

### Steps to reproduce the issue

Pause and resume

### Your phone/tablet/androidTV model

Google TV

### Operating system version

Google TV

**Comment by courville** [comment]
Can you please detail your exact hardware setup (TV, AV receiver, way of connecting ARC etc...)?

**Comment by piter-pit** [comment]
Tv is TCL android 12 snow cone connected to Yamaha RX v6a via eARC. Is it only with my configuration? I remember similar issues some time ago when there was micro stuttering

Edit: https://github.com/nova-video-player/aos-AVP/issues/1298#issuecomment-2594659799 here. But now I'm not sure if rewind helps... Maybe

**Comment by courville** [comment]
https://github.com/nova-video-player/aos-AVP/releases/tag/v6.4.17 should be better.

**Comment by piter-pit** [comment]
> https://github.com/nova-video-player/aos-AVP/releases/tag/v6.4.17 should be better.

Not sure if there is anyway better. Maybe after rewind a little but still clearly noticable

**Comment by piter-pit** [comment]
Tested on EAC3 for
system encapsulation - same
Nova encapsulation - not working, buzzing sound
Disabled - no 5.1 but in sync always

On AAC stereo there is slight out of sync even on system encapsulation

**Comment by courville** [comment]
Back to timestamp based audio latency dynamic estimation with https://github.com/nova-video-player/aos-AVP/releases/tag/v6.4.18 but fixing pause/play former issue. Is the sync any better? It is for me on the nvidia shield.

**Comment by piter-pit** [comment]
Not really, still a lot after pause resume. But I have feeling that from the begging it's a little bit out of sync (like 0,1s). On system encapsulation after pausing also a lot difference for eac3

**Comment by courville** [comment]
@piter-pit ok thanks for the testing.
I cannot reproduce the pause/play issue anymore but I will try with other devices.
Just to be clear when you were on 6.4.17 (the previous release) you still had the pause/play huge delay compared to bare play (this should not happen)?

**Comment by piter-pit** [comment]
Yes it was very similar, for all 3 versions. I think when I hit pause the video stops and after some moment audio. When resumed both start in pretty much the same time. Let me know if I can help with testing somehow

**Comment by piter-pit** [comment]
That is strange that it work fine on Nvidia shield and not on my setup... You have 5.1 surround, right?

**Comment by esnnn** [comment]
Same here on Sony kd-55x81j, Google TV. 
Looks like mostly 4k video problem - pause/resume resulting in audio goes out of sync. When the pause button pressed the video still playing for a some time like 0.5 sec. and the synch offset looks like this 0.5 sec too. With or without "Android frame timing".

**Comment by piter-pit** [comment]
In my case it was 1080p

**Comment by piter-pit** [comment]
Hi @courville I've noticed that in newest release when I play video with EAC-3 audio (Dolby Digital Plus) in nova it is converted to AC-3 (Dolby Digital) not sure if it's needed? Also I think there is little out of sync even without pausing (I saw the note that play/pause/play is still on going)

**Comment by courville** [comment]
> Hi [@courville](https://github.com/courville) I've noticed that in newest release when I play video with EAC-3 audio (Dolby Digital Plus) in nova it is converted to AC-3 (Dolby Digital) not sure if it's needed? Also I think there is little out of sync even without pausing (I saw the note that play/pause/play is still on going)

The rationale is twofold: i) being able to benefit from audio filters like audio boost or night mode in the recoding even for (E)AC3 tracks in the original video, ii) have a less complex code handling exceptions.

**Comment by piter-pit** [comment]
@courville so it's not a bug, it's a feature 😄
Ok, I thought it might be unexpected

**Comment by courville** [comment]
@piter-pit, also please disable android sync experimental option. I have tried another way that should get smoother video without it. If you see issues please report them (audio speed disabled: I am reworking this too).

**Comment by piter-pit** [comment]
@courville with Android frame timing disabled I have some issues with video smoothness it gets kind of hiccups like here
https://streamable.com/5ulsqv

When enabled it's smooth but I need to add like ~100ms audio delay

**Comment by courville** [comment]
@piter-pit strange I do not have delay on my side even with sound bar but not tried with android TV TV with eARC.
Regarding smoothness, is it linked to a specific video or systematic? If you have a sample it would be nice (ffmpeg extract 1mn).

**Comment by piter-pit** [comment]
@courville hippups are on all videos I play (when android timing is disabled) even stereo and even on internal speakers (no AVR)
When I changed decoder (video) from default to android media player there are no hippups but also no 5.1 sound (even supported EAC3)

**Comment by piter-pit** [comment]
I can upload a sample but not sure if it will help if problem is with all

**Comment by courville** [comment]
And without soundbar connected it is playing smooth?

**Comment by piter-pit** [comment]
@courville, I just changed output in tv settings but give me a moment I will disconnect HDMI 

> And without soundbar connected it is playing smooth?

**Comment by piter-pit** [comment]
Ok... It looks better when AVR is physically disconnected + I've noticed that on the test video each time ball bumps there should be a sound and in nova there a 3 sounds and next is silent, then again 3 sounds and again... And again

Omg...

**Comment by courville** [comment]
> Ok... It looks better when AVR is physically disconnected + I've noticed that on the test video each time ball bumps there should be a sound and in nova there a 3 sounds and next is silent, then again 3 sounds and again... And again
> 
> Omg...

really strange...

**Comment by piter-pit** [comment]
That doesn't look promising 😁 but let me know if any further testing is needed. Btw checked on different player and the bump should be audible each time

**Comment by courville** [comment]
I checked on my side on an android TV and and nvidia shield or other boxes, I have no such issue. We really need to understand what differs in your settings. Can you reproduce passthrough disabled, audio speed disabled, android sync disabled?

**Comment by piter-pit** [comment]
@courville when passthrough is disabled I have only stereo but it works ok. There is no stuttering and the sound is on every bump. The rest options ale also disabled

**Comment by piter-pit** [comment]
Hi @courville you probably have already info that from version 19 or 20 there are some sound issues. Just checking version 22 and here is the summary, hope it will help you anyhow
1. Passthrough: nova encapsulation
a.video with EAC-3 supported by AVR - only clicking noise (AVR detects as stereo PCM, TV does not support multichannel PCM - only stereo)
b. Video with AAC 5.1 - stereo, but ok as long as you not pause then out of sync
2. System encapsulation
a. EAC-3 sound ok 5.1 but some out of sync and maybe video stuttering appears during watching without pausing, after pause similar - not worse
Android timing helps until you pause then clear out of sync
b. AAC 5.1 - only stereo
3. Universal AC3 recoding
EAC-3 and AAC 5.1 only clicking noise

**Comment by courville** [comment]
> Hi [@courville](https://github.com/courville) you probably have already info that from version 19 or 20 there are some sound issues. Just checking version 22 and here is the summary, hope it will help you anyhow
> 
> 1. Passthrough: nova encapsulation
>    a.video with EAC-3 supported by AVR - only clicking noise (AVR detects as stereo PCM, TV does not support multichannel PCM - only stereo)
>    b. Video with AAC 5.1 - stereo, but ok as long as you not pause then out of sync
> 2. System encapsulation
>    a. EAC-3 sound ok 5.1 but some out of sync and maybe video stuttering appears during watching without pausing, after pause similar - not worse
>    Android timing helps until you pause then clear out of sync
>    b. AAC 5.1 - only stereo
> 3. Universal AC3 recoding
>    EAC-3 and AAC 5.1 only clicking noise

Thank you for the detailed feedback: I assume that this is with your TCL TV connected via eARC to AV receiver (I have not tested this configuration yet, I validated all passthrough modes on google streamer 4k and nvidia shield).

Android frame timing needs to be disabled for now since it causes AV desync after pause/resume and this one I have hard time to fix until now.

**Comment by courville** [comment]
@piter-pit can you please post a picture while playing the video of the tile dedicated to information that discloses hardware/software decoding + the screen capabilities and the AV receiver capabilities (next to audio and subtitles tiles)?
Do you also confirm that you have disabled "force audio passthrough" in nova settings?

**Comment by courville** [comment]
For eARC we need other methods that I have been implementing so far. I will add these.

**Comment by piter-pit** [comment]
@courville forced passthrough is disabled.
Tv setup is as you said. I can try mi box if it would help

![Image](https://github.com/user-attachments/assets/06d60711-5180-4e13-a4c4-c6ee5baa8f84)

**Comment by courville** [comment]
> [@courville](https://github.com/courville) forced passthrough is disabled. Tv setup is as you said. I can try mi box if it would help

Thx for the info, it means that capability wise it is detected via eARC (good news).
I expect that you would have better passthrough experience now with mibox (at least I hope with 6.4.22 since it is not eARC).

I will blindly work on eARC (since I do not have a setup to reproduce) and provide test builds for you to test if you are ok (unless a kind donator ships me a TV...).

**Comment by piter-pit** [comment]
Sure, I can check. I didn't expect there is so much difference unless sending something that regular arc does not support eg multichannel PCM

**Comment by courville** [comment]
Your eARC should support 8 PCM channels...

**Comment by courville** [comment]
@piter-pit, one more experiment for you: can you please try the passthrough with force passthrough enabled in nova settings?
I suspect that the wrong sound is nova sending PCM and telling it is compressed audio.

**Comment by piter-pit** [comment]
@courville with forced passthrough enabled
Universal AC3 recoding display cannot play audio track for eac3 or AAC 5.1
For nova encap: eac3 cannot play audio and for AAC 5.1 only stereo.
For system: eac3 is playing 5.1, AAC 5.1 is in stereo so es expected

**Comment by courville** [comment]
OK, important finding: ENCODING_IEC61937 is not reported as capability on your TV, it means that passthrough mode 1 will never work (you will always hear clicking noise). This probably means that I should never do "universal" passthrough mode 3 (ac3 encoding) relying underneath on mode 1 but that will make it unusable on Mediatek based hardware like google streamer 4k...

**Comment by courville** [comment]
> [@courville](https://github.com/courville) with forced passthrough enabled Universal AC3 recoding display cannot play audio track for eac3 or AAC 5.1 For nova encap: eac3 cannot play audio and for AAC 5.1 only stereo. For system: eac3 is playing 5.1, AAC 5.1 is in stereo so es expected

Thanks for the testing. I need to disable nova encapsulation on your setup because ENCODING_IEC61937 is not reported. This means that it will never work. And since ac3 recoding passthrough relies on nova encapsulation, I need to reroute it to android encapsulation to make it work too.

**Comment by piter-pit** [comment]
@courville Is this related to lack of multichannel PCM support on tv even when eARC and AVR supports it? I know that most android tvs do not support it

**Comment by courville** [comment]
@piter-pit I am ready to share a build, is your tv arm64 or arm32?

**Comment by courville** [comment]
For testing [arm64](https://drive.google.com/file/d/1faNEp1-8RC-rqUI7fSLSQBnYkd3T45fg/view?usp=sharing) and [arm32](https://drive.google.com/file/d/1P-2R8U6nMEcP9Typ7FQ16KmokXh-wMbV/view?usp=sharing) (blind coding and no testing for eARC but with I expect sound logic...).

**Comment by piter-pit** [comment]
Arm32, forced pass disabled, AC3 recoding: EAC3 and AAC 5.1 both clicking noise
For system: eac3 is playing 5.1, AAC 5.1 is in stereo
Forced enabled, AC3 recoding: eac3 and AAC -> cannot play audio track

**Comment by courville** [comment]
What I do not get is why you have only stereo on eARC it should support in theory multichannel PCM. Instead of assuming 2CH like in your report, I will query `AudioManager.isDirectPlaybackSupported` with PCM 5.1 and 7.1 and revert to 2CH if it is false (in final implementation).

**Comment by piter-pit** [comment]
@courville I've heard that a lot of tvs, especially android but not only does not support multi pcm. Chat says that in is case of
Android phones, tablets, and TVs use the same architecture:

Every app → sends audio to AudioFlinger

AudioFlinger mixes audio into stereo PCM

**Comment by courville** [comment]
@piter-pit sorry for the repeated tests, another try https://drive.google.com/file/d/1ZoZEgHxMNOU93NNPL7dpNVwSgDMQtfbz/view?usp=sharing

**Comment by piter-pit** [comment]
@courville,
forced pass disabled, AC3 recoding:
EAC3 works
AAC 5.1 works but in my test video after 3 bumps, 4rd one is silent and I've noticed that on AVR I have icons showing current speaker setup and it disappears on 4th bump
For system: eac3 is playing 5.1, AAC 5.1 is in stereo
Forced enabled, AC3 recoding: eac3 and AAC -> cannot play audio track

**Comment by piter-pit** [comment]
https://streamable.com/wop0se

**Comment by piter-pit** [comment]
Different player is fine, checked again since I've created this file by myself 😄 https://streamable.com/4kj6bk

**Comment by courville** [comment]
@piter-pit thx for the testing and the videos are helping understanding your comments and the meaning of "bump". However this is really strange. I will investigate.

**Comment by courville** [comment]
> forced pass disabled, AC3 recoding: EAC3 works AAC 5.1 works but in my test video after 3 bumps, 4rd one is silent and I've noticed that on AVR I have icons showing current speaker setup and it disappears on 4th bump 

OK I found the issue in the code that triggers this behavior. I will fix it. Thanks for pointing this out.

> For system: eac3 is playing 5.1, AAC 5.1 is in stereo

This one works as intended.

> Forced enabled, AC3 recoding: eac3 and AAC -> cannot play audio track

OK I should not force IEC flag on IEC-less eARC otherwise I cannot fallback to android encapsulation and use nova encapsulation still that requires IEC. Easy to fix

**Comment by courville** [comment]
@piter-pit could you please test this apk that should address your concerns https://drive.google.com/file/d/1DjCFD_6GX7HGaro2iEHAa8inftosf5_E/view?usp=sharing
I must admit I pushed my luck a bit adding one additional change that could create a regression (probing multichannel PCM on eARC from Android side where we know that it is limited to 2 channels but could be more in the future).

**Comment by piter-pit** [comment]
@courville ok, so it looks similar, on AC3 recoding in this test video there is still 4th bump silence no matter if forced passthrough is enabled or disabled
Eac3 seems to work

**Comment by courville** [comment]
Thx for the report and testing. Thus it seems that my AC3 recoding sink churn fix is not enough.

**Comment by piter-pit** [comment]
@courville another strange behavior is that this audio channel indicator visible on AVR on the video happens only on this test video (and missing bump sound). I do not see it disappears on regular video nor mutting sound. Maybe silence is detected and some switching happens or since I encoded this video myself was done incorrectly, but on the other hand, other player works fine...
In addition, it will not bring anything to this issue but in HBO max app (not always, but) sometimes happen that video freezes after forward backward scrolling or skipping intro - I need to exit enter video, not the player. Netflix, Disney nor Prime has no such issue.

**Comment by esnnn** [comment]
6.4.23 works just perfect/synced/ after pausing or ff/seek in stereo with android frame timing. Hope 5.1 will be the same! (passthrough options are greyed out in settings)!

**Comment by courville** [comment]
@esnn, could you please detail your exact configuration (tv, if you have an AV receiver etc.)?
If the passthrough options are greyed out it is because nova assesses or android reports (wrongly perhaps) that your hardware has no audio passthrough capability (it can still do multichannel 5.1 PCM for example but not with audio passthrough).

**Comment by esnnn** [comment]
> [@esnn](https://github.com/esnn), could you please detail your exact configuration (tv, if you have an AV receiver etc.)? If the passthrough options are greyed out it is because nova assesses or android reports (wrongly perhaps) that your hardware has no audio passthrough capability (it can still do multichannel 5.1 PCM for example but not with audio passthrough).

Sony kd-55x81j Google TV Android 12 TV. Yamaha rx-v440 AV receiver. I do remember the DD or DTS 5.1 indicators on receiver and passthrough enabled in Nova previous builds. Hope it will be back some day! 

Just get 4.24 - I'll check it a bit later!

**Comment by courville** [comment]
@esnnn, thanks. Do you use HDMI betwenn yamaha and tv (I guess earc)?

**Comment by courville** [comment]
Thinking about it, in CustomApplication the capability detection had two issues for ARC/eARC TV setups:
 
- It only treats AudioDeviceInfo.TYPE_HDMI as “HDMI”, but on Android TV with an AVR over ARC/eARC the active output is often reported as TYPE_HDMI_ARC / TYPE_HDMI_EARC.
- the initial device scan effectively only looks at the first output device (due to an unconditional break in the loop), so if the first device was TV speakers, HDMI can be never detected

I will fix this.

**Comment by esnnn** [comment]
> Do you use HDMI betwenn yamaha and tv (I guess earc)?

no, S/PDIF Optical output, yamaha is pretty old and does not have arc
+ btw 4.24 build works just the same - no passthrough available.

**Comment by courville** [comment]
Thanks for sharing the information. Spdif detection is thus not working. Will share a test build soon

**Comment by esnnn** [comment]
> Will share a test build soon

glad to hear! you can count on me in case you need to install/check/test something

**Comment by piter-pit** [comment]
Hi @courville, many thanks for hard work and new version 🙂 I see that you have tried to fix that audio issue but in my case when AC3 recoding is used, no matter audio format I hear only klipped noise - checked even stereo files. When switched to system encapsulation the sound gets back to normal and no more stuttering video 💪💪 although when paused or rewind the sound gets out of sync, disabling android frame timing doesn't help

**Comment by piter-pit** [comment]
@courville I've just checked newest version 6.4.27 and I still have this https://vidplay.io/watch/hpVy2Z
AVR detects it as stereo

**Comment by courville** [comment]
@piter-pit, if I share a debug build with you, would you be able to share logcat debug logs with me (https://github.com/nova-video-player/aos-AVP/wiki/Debugging)?

**Comment by piter-pit** [comment]
@courville never did it before but I can try.
Btw just installed recent release and I have same situation

**Comment by courville** [comment]
> [@courville](https://github.com/courville) never did it before but I can try. Btw just installed recent release and I have same situation

Here is the test apk: https://drive.google.com/file/d/1tUWjVXB3mFalJs5bTh7QwdFid_6UkeJn/view?usp=sharing 
Any logs with:
- CustomApplication refreshAudioOutputCapabilities(...) device encodings list
- CustomApplication updateIecEncapsulationCapability: isIecEncapsulationCapable=...
- PlayerActivity log: PCM diagnostic - ... isIecCapable=...

Those logs will tell us whether Nova thinks IEC is supported at the time of playback (which is consistent with garbled sound).

**Comment by piter-pit** [comment]
@courville Ok, a was able to connect to tv. I will try to bring some logs tomorrow. Do I need to try to play some AV file to collect it?

**Comment by courville** [comment]
> [@courville](https://github.com/courville) Ok, a was able to connect to tv. I will try to bring some logs tomorrow. Do I need to try to play some AV file to collect it?

Please capture the log at application start and start playing the stream while collecting logs.
On powershell: `adb logcat --pid=$(adb shell pidof -s org.courville.nova)` or in cmdline `for /f %p in ('adb shell pidof -s org.courville.nova') do adb logcat --pid=%p` (never tried this one) should provide expected results.

**Comment by piter-pit** [comment]
@courville OK, I have linux so I used `adb logcat | grep org.courville.nova > nova_log.txt` and interesting thing: I ran 3 files:
1st that bouncing ball which couldn't play. It opened paused and AVR displayed stereo
2nd video with EAC3 5.1 audio: it played with that strange sound
3rd video with AAC 5.1 audio: it played with that strange sound

**Comment by courville** [comment]
@piter-pit thanks for managing to get logs!
Unfortunately, I do not see any of the actionable information the logs that should have been present (IEC) using the test build provided.
Let me check if I did something wrong.

**Comment by piter-pit** [comment]
@courville different grep? Or is it directly from nova?

**Comment by courville** [comment]
The apk I shared should have provided information such as (this is for the emulator not an hdmi capable device):
```
com.archos...pplication org.courville.nova                   D  getSupportedAudioCodecs: audioEncodingFlag=0
com.archos...pplication org.courville.nova                   D  refreshAudioOutputCapabilities(devicesAdded): device type=2 name=sdk_google_atv64_amati_arm64 maxChannels=0 encodings=
com.archos...pplication org.courville.nova                   D  getEncodingFlags: encodings=-1, encodingFlags=[], allHdmiAudioCodecs=0
com.archos...pplication org.courville.nova                   D  getSupportedAudioCodecs: audioEncodingFlag=0
com.archos...pplication org.courville.nova                   D  refreshAudioOutputCapabilities(devicesAdded): device type=18 name=sdk_google_atv64_amati_arm64 maxChannels=0 encodings=
com.archos...pplication org.courville.nova                   D  updateIecEncapsulationCapability: isIecEncapsulationCapable=false
com.archos...pplication org.courville.nova                   D  updateDirectPcmMultichannelCapability: API<29 or no HDMI, setting false
```
The apk shared should have been able to output this. Can you please check nova version displayed in settings?

**Comment by piter-pit** [comment]
@courville 6.4.28 (20260216.1956)

**Comment by courville** [comment]
> [@courville](https://github.com/courville) 6.4.28 (20260216.1956)

this is the right one thus the error is on my side.

**Comment by courville** [comment]
OK let's try again, new apk extended code: https://drive.google.com/file/d/1fY0uABn7dh1Lq6uyYsE0YZPlargW97b0/view?usp=sharing
Please share all the logs related to CustomApplication.

**Comment by piter-pit** [comment]
@courville 3.88MB? Is it correct?

**Comment by courville** [comment]
It is 32.7MB on my side

**Comment by piter-pit** [comment]
@courville yup, my bad. It wanted to open as installer so I click on download but it was downloaded as ".apk - Google drive" with 3,88MB. It's ok now.

**Comment by piter-pit** [comment]
[nova_log.zip](https://github.com/user-attachments/files/25415184/nova_log.zip)

@courville OK, but again, not sure if there is what you are looking for
This time every video was played, slightly different order
1. video with AAC 5.1 audio: it played with that strange sound
2. video with AAC 5.1 audio: it played with that strange sound
3. video with EAC3 5.1 audio: it played with that strange sound

**Comment by courville** [comment]
In your log capture it seems that we are missing the start of the application, i.e. I get logs when things are played (perhaps your tv is verbose and wipes logs after a while). Please check that you get `com.archos.mediacenter.video.CustomApplication` tag logs when opening the application.

**Comment by courville** [comment]
Let me provide another apk with all the logs tagged WARNiNG to be sure.

**Comment by piter-pit** [comment]
I intentionally killed app and than start while logging was ongoing, however it was something with old dates. Let me double check

**Comment by piter-pit** [comment]
com.archos.mediacenter.video.CustomApplication this might not be visible in log due to grep? Let me add it. Should I check on this APK or you want to provide new one?

**Comment by courville** [comment]
New apk https://drive.google.com/file/d/1kY58nIext4DPyofz7r1HUIX0hJHS_qry/view?usp=sharing all logs in warning that are displayed by default. I tested all recent apks and logs should have been there. Check that nova version is indeed 6.4.28-20260219.1342.

**Comment by courville** [comment]
ok this is indeed the grep... Please grep CustomApplication instead

**Comment by piter-pit** [comment]
@courville
ok, now log from `adb logcat | grep -E "org.courville.nova|com.archos.mediacenter.video.CustomApplication" > nova_log.txt`

log contains:

time 13:44-13-46: 6 runs: AAC -> AAC -> EAC3 -> switch from recoding AC3 to system encapsulation -> AAC -> AAC -> EAC3

time 13:50-13-54: 4 runs: AAC -> EAC3 -> switch from recoding AC3 to system encapsulation -> AAC -> EAC3

[nova_log.zip](https://github.com/user-attachments/files/25416559/nova_log.zip)

**Comment by courville** [comment]
Stay tuned

**Comment by courville** [comment]
Could you please try this apk: https://drive.google.com/file/d/1Ml48HWMX1GEHr4pW2DYoPZw5EaKB2cMi/view?usp=sharing

**Comment by piter-pit** [comment]
@courville the sound is now more like noise than before https://imgur.com/a/djYWJct , still discovered as stereo by AVR. Any log I can drop tomorrow if you need

**Comment by courville** [comment]
Damn I thought I found something. This is tricky since I do not have and Android TV TV to test... Will add more logs on the avos native part to progress...

**Comment by courville** [comment]
Could you use this apk to generate logs when playing one file https://drive.google.com/file/d/1lSDz54be9cvpZwvAt8bTACs8kW-56CSz/view?usp=sharing ? This will output a ton of logs but I will need these to understand how audiotrack is configured. No need to play for long.

**Comment by piter-pit** [comment]
@courville have a look

**Comment by courville** [comment]
@piter-pit, sorry for the long delay before getting back to you.
The last logs provided unfortunately does not contain any `avos_player:` debugs that should have been there.
Let me share a new debug build to be extra sure that you are using the good one.
Can you please try this [arm64 apk](https://drive.google.com/open?id=1asXJCs9I0a-AC7URC5C5VEKdDe5CEIhY) or [arm32 apk](https://drive.google.com/open?id=1oiHKNiq4ilHVrVNtBzajIVUrowMVLoC9) depending of your architecture and provide adb logcat logs. I have updated https://github.com/nova-video-player/aos-AVP/wiki/Debugging section. Note that it should provide a lot of `avos_player:` logs in the file, if you do not see any or a few ones it means that something is wrong.

**Comment by piter-pit** [comment]
Maybe again grep - I will add it and let's see.

**Comment by piter-pit** [comment]
@courville There is a lot related to avos_player - I hope this will help
For the reference: cli is `adb logcat | grep -E "org.courville.nova|CustomApplication|avos_player" > nova_log.txt`

**Comment by courville** [comment]
Logs helped thanks. I make some blind fixes (still not having access to proper device). Can you please try this [arm64 apk](https://drive.google.com/open?id=1fdYzNzbqDrnII7V7oJg1qPGOkeK2CJ_v) or [arm32 apk](https://drive.google.com/open?id=1-k_aQzrKEkzQBC15eZAqsF9h6SN44rgV) depending of your architecture and report if it helps? It still contains verbose logs.

**Comment by piter-pit** [comment]
@courville OMG it works!! Let me do some more testing but it really looks promising 🙂 do you want logs from this version?

**Comment by courville** [comment]
@piter-pit nice to hear. If your AV receiver displays that it is dolby this is fine. I will provide a build without logs so that you do not suffer from any performance penalty.

**Comment by Macusercom** [comment]
@courville 

Coming from #1662: With this test version (https://drive.google.com/open?id=1fdYzNzbqDrnII7V7oJg1qPGOkeK2CJ_v) I still get the issue that I can't change the audio delay no matter what. Though AC3 re-encoding is fixed now for me.

I captured all relevant logs and it doesn't matter if I disable audio passthrough, use system encapsulation or AC3 re-encode: https://drive.google.com/drive/folders/1dMx8W6XiN147yik1NMMZ4hf_y07jZIvN?usp=drive_link

nova_log_*.txt features the three different audio passthrough settings. It worked fine with v6.4.19 but broke with 6.4.28.

EDIT: I tested again with the build from https://github.com/nova-video-player/aos-AVP/issues/1552#issuecomment-3979910481 and added it to the linked folder as "build2.log". It still doesn't work and avos_player reports:

`avos_player: audiotrack_get_delay(0xf0b1f4b0): Using static latency for passthrough: 782 ms`
`avos_player: audiotrack_get_delay(0xf0b1f4b0): get_delay: src=static(passthrough) ret=782 latency=782 fallback=-1 delay=-1 ts_use=0 streak=10  `
`avos_player: aud_at_delay: src=static(passthrough) ret=782 delay_valid=1 latency=782 fallback=-1 delay=-1 ts_use=0 streak=10`

I have changed the audio delay from 0 ms to a negative offset and switched to a positive while waiting a few seconds. It does not change at all unfortunately

**Comment by piter-pit** [comment]
> I will provide a build without logs so that you do not suffer from any performance penalty.

@courville will you update release version or still testing?

**Comment by Macusercom** [comment]
I have now pin-pointed it to version 6.4.22. There it worked, with 6.4.23 audio delay completely breaks. I have added two new logs from the working version here (https://drive.google.com/drive/folders/1dMx8W6XiN147yik1NMMZ4hf_y07jZIvN?usp=drive_link)

**Comment by courville** [comment]
@Macusercom when you say "audio delay" you are referring to configuring a fixed audio delay on nova via audio menu right?

**Comment by Macusercom** [comment]
@courville Yes, manually setting an audio delay doesn't work anymore. Sometimes audio seems to be slightly out of sync so it is impossible to fix that since 6.4.23

**Comment by courville** [comment]
@Macusercom, can you please try this [arm64 apk](https://drive.google.com/open?id=1Kg3DsLxu6Oha1DRUC56Bhvnz2O2u_K4u) or [arm32 apk](https://drive.google.com/open?id=1azxzCV-QQQMgTPezjftgCbJHMUyoqSdK) depending of your architecture and report if it helps?

**Comment by Macusercom** [comment]
@courville Tested with arm32.apk but it still does not work unfortunately. Same behaviour: it doesn't change the audio delay

**Comment by piter-pit** [comment]
@courville hi, after some more testing I agree that delay might need some adjustment like <100ms, but the video is no longer out of sync after pause.
What I noticed is that on regular movie it's working ok, on the test video of bouncing ball every 4th bump is silent and AVR is getting lost on audio input, there is no such effect on different player. You probably need logs for this ? 🤔

Edit: just checked latest release on normal video and there is definitely noticable time delay - even more than 100ms. Checked again on that bouncing ball and it's like 300ms

**Comment by esnnn** [comment]
6.4.30 is a big step forward! Passthrough is back, but with some notes:

- with "system encapsulation" in passthrough options Nova plays ordinary dd/dts perfectly, but no sound on dts-hd/dolby true hd/dd+
- with "AAC reencode" all this "true/hd/+" tracks are playing but out of sync and I can't "fix" them like it was in old versions - just click on "back" button once to make nova "catch" the sync again. + Selecting other tracks takes a long time and it looks like the whole player stuck for a 30 seconds. 

Looks like it lacks an option like "extract dts core" or "convert Dolby+ to Dolby" - whatever option to "Convert Dolby TrueHD/E-AC3) to standard Dolby Digital (AC3) 5.1"

**Comment by Macusercom** [comment]
> 6.4.30 is a big step forward! Passthrough is back, but with some notes:
> 
> * with "system encapsulation" in passthrough options Nova plays ordinary dd/dts perfectly, but no sound on dts-hd/dolby true hd/dd+
> * with "AAC reencode" all this "true/hd/+" tracks are playing but out of sync and I can't "fix" them like it was in old versions - just click on "back" button once to make nova "catch" the sync again. + Selecting other tracks takes a long time and it looks like the whole player stuck for a 30 seconds.
> 
> Looks like it lacks an option like "extract dts core" or "convert Dolby+ to Dolby" - whatever option to "Convert Dolby TrueHD/E-AC3) to standard Dolby Digital (AC3) 5.1"

Thanks for the info! I tested it now and Dolby Vision content seems to stutter a lot now when audio passthrough via system encapsulation is enabled. AC3 re-encode seems to work fine. Rolled back to 6.4.22 and DV content is smooth with system encapsulation.

It isn't a slight stutter, it freezes every 1-2 seconds for 0.5 seconds

**Comment by courville** [comment]
I think I found one crash root cause.
Regarding the TrueHD, I think the problem is the TrueHD's 40-sample native frame size which spams the current audio pipeline causing stuttering.
The only solution there is to perform a post-filter PCM accumulation to not overload audiotrack.

**Comment by courville** [comment]
No sound on TrueHD regression fixed.

**Comment by courville** [comment]
> Thanks for the info! I tested it now and Dolby Vision content seems to stutter a lot now when audio passthrough via system encapsulation is enabled. AC3 re-encode seems to work fine. Rolled back to 6.4.22 and DV content is smooth with system encapsulation.

@Macusercom I am suspecting that this is note dovi related (Dolby Vision) and could be related to more the audio track for the specific video.
Could you please let me know the audio codec used? Is this TrueHD?

**Comment by Macusercom** [comment]
ffmpeg reports: eac3 (Dolby Digital Plus + Dolby Atmos), 48000 Hz, 5.1(side), fltp, 576 kb/s (default) (original) so it is Dolby Atmos. I have added logs if this helps

EDIT: It seems that it does play smoothly with Android Frame Timing enabled but does not with it disabled. However, with 6.4.22 it worked fine either way (except maybe one slight one frame stutter every few seconds). Now with 6.4.30 you must enabled Android Frame Timing

[build.log](https://github.com/user-attachments/files/26080693/build.log)

**Comment by piter-pit** [comment]
@courville I think it works with new release 🙂 although I see when I exit nova and want to open it again I cannot. I need to kill it in app manager and then open.

**Comment by courville** [comment]
> [@courville](https://github.com/courville) I think it works with new release 🙂 although I see when I exit nova and want to open it again I cannot. I need to kill it in app manager and then open.

I do not reproduce this. You confirm that it is on your TCL android tv? What are the audio modes you are using (passthrough, android frame sync, audio speed atempo/audiotrack)?

Can you get logs of the crash or when you try to open the app?

**Comment by piter-pit** [comment]
I will get you a log, however I might have been to fast since it get a little out of sync after some time of watching with both android timing on or off. I will try to summarize it.
The icon is different, with black circuit around 🤔
@courville I see that version .31 was dropped - do you still want logs?

**Comment by courville** [comment]
> I will get you a log, however I might have been to fast since it get a little out of sync after some time of watching with both android timing on or off. I will try to summarize it. The icon is different, with black circuit around 🤔 [@courville](https://github.com/courville) I see that version .31 was dropped - do you still want logs?

I will provide a build with logs for you to provide more meaningful inputs.
I removed the release because some users on android tv tv sets have no sound surprisingly.

**Comment by courville** [comment]
> [@courville](https://github.com/courville) I think it works with new release 🙂 although I see when I exit nova and want to open it again I cannot. I need to kill it in app manager and then open.

Can you please elaborate a little more about "cannot open nova again"? When you open nova again are you stuck with a black/blue screen, do you access the main activity, you cannot play video?
My guess is that on your specific setup the avos  is stuck in native close or half-dead player state.

**Comment by piter-pit** [comment]
@courville strange, today where is no issue with that... Yesterday when I returned to android tv main screen I couldn't start nova again and the icon was with black circuit. Had to go to settings - applications, find nova and force shutdown. But again non of this happen today

**Comment by courville** [comment]
This is strange this "black circuit icon". Please take a picture next time you get it. Must be TCL specific behavior freezing nova for some reason.

**Comment by piter-pit** [comment]
@courville i'm not able to reproduce it anymore. Moreover I see no out of sync even after some time of watching. Maybe it required tv restart after update...

**Comment by courville** [comment]
Please try out https://github.com/nova-video-player/aos-AVP/releases/tag/v6.4.31 (yet another 6.4.31...)

**Comment by piter-pit** [comment]
@courville the newest .31 I had to set manually audio delay about +150-200ms, and it was consistent over the entire video (it was with EAC3)
However when I switch video that has AAC 5.1 sound I had to set ~+500ms.
Moreover when I tested on "bumping ball test" I had to set once -600ms (with minus) and after testing some different files 0ms was perfect on a same video to be in sync and I still notice that AVR loosing audio input Information after some bumps.
So I tried switching between videos and rewinding and frankly I cannot find a pattern, then I played again video with AAC and then 0ms was perfect, then rewind few seconds back and out of sync appeared and I could rewind further and it was repetitive...

**Comment by piter-pit** [comment]
@courville ok, made a video to show you what is going on
[https://streamable.com/ksgslj](https://streamable.com/ksgslj)
look at the video it is AAC 5.1 with recoding:
0:00 there is first and last block only which means stereo (front and subwoofer)
<img width="118" height="41" alt="Image" src="https://github.com/user-attachments/assets/8eccfa63-ab77-464f-a8ec-bd55c601bec8" />
0:04 - AVR detects input signal 5.1 but audio is out of sync about 600 ms
<img width="120" height="44" alt="Image" src="https://github.com/user-attachments/assets/6fcb18b8-3a47-4f23-a8d3-9e351c8102b7" />
0:11 - AVR loosing input signal information have look on the AVR display
<img width="120" height="44" alt="Image" src="https://github.com/user-attachments/assets/98c5c86b-4824-4821-9762-733068333e65" />
0:14-0:20 I'm trying to rewind to the begging
0:21+ audio and video are at sync
0:27 ARV loosing input signal information
then I opened "normal" video with AAC 5.1 and initially it was perfectly sync and 0ms delay was needed, but after rewinding for a few seconds it was out of sync
Then I opened another video with EAC3 5.1 and again at the beginning 0ms is ok and after rewind it is also ok
Let me know if you need any logs...

**Comment by courville** [comment]
@piter-pit still on AC3 recoding passthrough or for mode 2?
Can you please also provide me the link to download your testing video (perhaps you did in the past but I forgot).

**Comment by esnnn** [comment]
Updated to .31 over the installed .30. Right After the update almost nothing works., but it getting better after TV restart.
Got the file with DV video and 3 audio tracks  - Dolby TrueHD, Dolby , Dolby Digital Plus and DTS-HD MasterAudio.

**With "system encapsulation" **
-all three track are muted and small message with blue icon like "Cannot play audio" shows at the screen bottom

**With "Universal (AC reencoding)"**
- all the tracks playing with "Dolby Digital" shown on AV receiver display even if I choose DTS track.
- it looks ok when you don't change the audio tracks - sync stays ok after pause
- it takes a while to change the tracks - no sound for 15 sec. approx.  After changing the tracks for couple of times video goes out of sync 
- also it looses the sync after long pressed seek button on tv remote  - if you skip ffw for a 10 minutes of video for example

**Comment by piter-pit** [comment]
@courville yes everything on AC3 recoding.
I switched for a moment on system encapsulation and it doesn't work and never worked - exit video after a moment and on the first one AAC 5.1 is in stereo and audio is synced. I can double check with rewinding and with EAC3 audio if you want but it was ok.

@esnnn universal AAC recoding works that way. Every audio - even supported by AVR is recoded to Dolby Digital (EAC3) and system encapsulation don't work for me either.
You also needed to restart tv after update?

**Comment by esnnn** [comment]
> [@esnnn](https://github.com/esnnn) universal AAC recoding works that way. 

yes it is, I've just made a note that DTS is currently unavailable in any way

> You also needed to restart tv after update?

yes! Nothing really worked right after the update - restart fixed a lot but , but system encapsulation just don' work at all and the AAC reenc have some questions

**Comment by piter-pit** [comment]
@esnnn some time ago I asked about recode of supported formats https://github.com/nova-video-player/aos-AVP/issues/1552#issuecomment-3478204910 and in feature suggestion I suggested solution like in Vimu where you select specific formats you want to recode and output format to which you want to recode https://github.com/nova-video-player/aos-AVP/issues/1296 and it was some issue with filters and it was better from compatibility point of view to make all formats recoded. Maybe in the future 😉

**Comment by piter-pit** [comment]
@courville just tested recent .32 version and as I still see on test video that for a moment AVR looses audio input information and mute itself for one bump sound this is not visible on a regular video.
I was testing it at the beginning and when I have enable android frame timing enabled there was no issue with sync. When disabled it was ~0,5 sek need for correction.
Today when I opened the player to test it firmly just after open the video was way out of sync... Small rewind and it was back on truck. I don't understand why it is so inconsistent. Maybe the key is in this silence on test video and loosing audio input information. If you need I can prepare detailed log, but for that you would need to prepare app?

**Comment by piter-pit** [comment]
I’m sure you are just about enough of me by now 😉 but I've just tested .33 and it's basically the same

**Comment by courville** [comment]
> I’m sure you are just about enough of me by now 😉 but I've just tested .33 and it's basically the same

I found also some other corner cases that I just solved. Changing the global audio pipeline to get better sync with different options (android frame sync or not, dynamic delay or not, multiple passthrough mode) turns to be a nightmare to stabilize all the combinations.

To address your case I will share a build with debugs.
What I need is to know the exact configuration, (android frame sync on/off, audio speed on/off, atempo audio speed or audiotrack (even if you are on 1.0x), passthrough mode (I assume you are only using AC3 recode).
And please share your test video and specify if it happens with other ones as well (normal tvshow or movie).
The problem also is that I do not have a setup to test with a tv set running android os connected to AVR...

**Comment by piter-pit** [comment]
@courville I believe there's a lot of dependencies, setups, codecs etc.
Please share - I will collect.
I've tested so far with android timing on and off similar result however with on it works better (as described earlier it is usually ok, some times it required rewind. With off it's out of sync)
Audio speed always normal. Passthrough with AAC recoding. I think I've checked normal and it worked ok on eac3 videos or stereo on AAC but in sync.
https://we.tl/t-eyaGtsu6Kvcrreth here you can download test video file. It does not happen on other videos, on the other hand this test video works well on different player.

**Comment by courville** [comment]
@piter-pit, can you please try this debug release [arm64 apk](https://drive.google.com/open?id=1XtQ68aM5VvoU06xVurt9ppDzdKV3s3FW) or [arm32 apk](https://drive.google.com/open?id=1rxFjVJgiEojWE4FaIqlWKjA1wh9H97s5) depending of your architecture and report `adb logcat` (cf. https://github.com/nova-video-player/aos-AVP/wiki/Debugging). Logs should be spammed with `avos_player` lines.
This will help debug the issue (since I do not have your configuration).

**Comment by piter-pit** [comment]
@courville hi, let me get back to you on Monday since we have holiday season 🥚 :)

**Comment by piter-pit** [comment]
@courville Please have a look. I initiated this test file, played till AVR input was reset, rewind to the beginning, play for a moment, returned to the main nova menu and started again.
I hope it will help

[nova_log.zip](https://github.com/user-attachments/files/26517329/nova_log.zip)

**Comment by Streamer-3** [comment]
https://github.com/nova-video-player/aos-AVP/issues/1718

was about to open a issue. It is happening in [v6.4.34 release](https://github.com/nova-video-player/aos-AVP/releases/tag/v6.4.34) as well. I am using nova as an external player to stremio on a TCL tv running android 12. This really sucks. To bring the sync back i have to skip forward by pressing remote button twice. Same set up as described in the above issue opened recently. 

@WileyTheCoyote

**Comment by piter-pit** [comment]
> I found also some other corner cases that I just solved. Changing the global audio pipeline to get better sync with different options (android frame sync or not, dynamic delay or not, multiple passthrough mode) turns to be a nightmare to stabilize all the combinations.

Hi @courville I wonder if latest .36 version includes this new pipeline you've mentioned?

**Comment by esnnn** [comment]
Build .36 is visually just the same as .35 - only "recode everything to DD" is working.
Delay in audio looks like set "by default" now.
+ I launch this build twice and it starts with "force audio passthrough" checkmark unchecked every time. First time after update I have reboot the TV and the "force audio passthrough" was "off" for some reasons and there were no sound at all until I check it.

**Comment by piter-pit** [comment]
@esnnn in my case it works similar to earlier versions - I have inconsistent audio-video delays. That's why I was asking if this already includes new pipeline but I assume not

**Comment by courville** [comment]
Just to let you know, I am still working on fixing the lipsync with again major changes requiring delicate rethinking and refactoring. Stay tuned.

**Comment by piter-pit** [comment]
> Just to let you know, I am still working on fixing the lipsync with again major changes requiring delicate rethinking and refactoring. Stay tuned.

Finger crossed ;)

**Comment by WileyTheCoyote** [comment]
@courville I did a quick test of 6.4.37

Lipsync looks really good at start of play with the default app settings, Passthrough Disabled, Dynamic Estimation ON.

My perception in 6.4.36 was that sync was off by a tiny amount. Whether that was true or not, it looks perfect now.

Regarding, Pause/Resume, it looks perfect.  I paused for varying lengths of time. Exiting and reopening the app and resuming play also looks perfect. I will report if anything changes.  And I´ll play with Passthrough (although I don´t need it) after returning from travel.

Cheers

**Comment by hotboy87** [comment]
from my initial testing of the new version 6.4.37, the audio synchronization issue after pausing and then resuming playback has been fixed.

I will put it on more tests and I will tell you

**Comment by piter-pit** [comment]
For me it is still inconsistent. At the beginning I tried this bumping ball test video and was great, played regular video and was quite decent although slight delay was visible (acceptable) then tried test video again and it was like 300-400ms just to be again ok on 4th try... And I still see that AVR mutes after few bumps. That is strange... I really hope that new pipeline will be the solution

**Comment by courville** [comment]
@piter-pit can you please report on real videos (not the test video)?

Note to self @piter-pit video is downloadable via `yt-dlp -f "298+140" https://www.youtube.com/watch?v=ENXiHkk299U -o "videos/%(title)s.%(ext)s"`

EDIT: on nvidia shield ac3 recoding passthrough it is in sync but I experienced once a desync with PCM decoding which I cannot reproduce now. With ac3 recoding I do not get any sound gap.

**Comment by piter-pit** [comment]
@courville yesterday when I was checking I played for a moment normal video it was ok, maybe 50-100ms off. Today I wanted to play different "normal" video with ac3 5.1 and it was seriously out of sync - like 0,5-1sek, to check it it is not something wrong with video on a different player it is ok - so similar to test video.
I use ac3 recoding.

**Comment by courville** [comment]
> [@courville](https://github.com/courville) yesterday when I was checking I played for a moment normal video it was ok, maybe 50-100ms off. Today I wanted to play different "normal" video with ac3 5.1 and it was seriously out of sync - like 0,5-1sek, to check it it is not something wrong with video on a different player it is ok - so similar to test video. I use ac3 recoding.

thx for the testing feedback. I made another sync fix so this is per say a different code but could you please provide `adb logcat` logs with this debug apk: [arm64 apk](https://drive.google.com/open?id=1UrXn0FP47qU_h2oU7uQvRKB5EcVt_-nC) or [arm32 apk](https://drive.google.com/open?id=1wBc1pvkiQM0XCiNZMYz5wEV-dIWeBzFV) depending of your architecture when you reproduce out of sync? 
Log should be verbose and contain a lot of `avos_player` lines.

I am confident if I can get the logs that I will be able to fix your issue.
I have no setup with Android TV, TV set directly hooked to AV receiver with eARC.

**Comment by piter-pit** [comment]
Hi @courville, have a look here. I played only one file with the bigger issue - it is AC3 (with 2 audio tracks - maybe this is an issue?) so I thought to switch to system encapsulation since my AVR can play it - but it's the same.

[nova_log.zip](https://github.com/user-attachments/files/28223529/nova_log.zip)

**Comment by courville** [comment]
> Hi [@courville](https://github.com/courville), have a look here. I played only one file with the bigger issue - it is AC3 (with 2 audio tracks - maybe this is an issue?) so I thought to switch to system encapsulation since my AVR can play it - but it's the same.
> 
> [nova_log.zip](https://github.com/user-attachments/files/28223529/nova_log.zip)

Thanks for taking the time to provide logs. It is clear that audiotrack `getLatency` is the one reporting a wrong estimate in your case. I may have a lead now to solve the issue.

**Comment by hotboy87** [comment]
> > [@courville](https://github.com/courville) yesterday when I was checking I played for a moment normal video it was ok, maybe 50-100ms off. Today I wanted to play different "normal" video with ac3 5.1 and it was seriously out of sync - like 0,5-1sek, to check it it is not something wrong with video on a different player it is ok - so similar to test video. I use ac3 recoding.
> 
> thx for the testing feedback. I made another sync fix so this is per say a different code but could you please provide `adb logcat` logs with this debug apk: [arm64 apk](https://drive.google.com/open?id=1UrXn0FP47qU_h2oU7uQvRKB5EcVt_-nC) or [arm32 apk](https://drive.google.com/open?id=1wBc1pvkiQM0XCiNZMYz5wEV-dIWeBzFV) depending of your architecture when you reproduce out of sync? Log should be verbose and contain a lot of `avos_player` lines.
> 
> I am confident if I can get the logs that I will be able to fix your issue. I have no setup with Android TV, TV set directly hooked to AV receiver with eARC.


I tested this version, and it is indeed much better than the previous one regarding the audio delay issue. However, unfortunately, it still happens occasionally when pausing playback and then resuming it again.

**Comment by courville** [comment]
Hi, please check https://github.com/nova-video-player/aos-AVP/releases/tag/v6.4.38
Big fat warning: as the release notes foreword highlights, this is yet another audio architecture. I think the fundamentals are a lot cleaner but this release is not to be considered as an incremental fix one.

**Comment by WileyTheCoyote** [comment]
@courville 

Got it, will test it out in the next day or 2.  Cheers

**Comment by WileyTheCoyote** [comment]
@courville 

Initial trial very positive.

Default app settings (no Passthrough, Dynamic estimation), excellent
Big improvement for my setup, Nova and System passthrough are excellent; Universal passthrough appears to have very small loss of sync, but I do not consider that a problem since the others are working, users who need passthrough have working options.

Regarding loss of sync during pause/resume, it looks excellent so far.  I want to test longer pauses.  Will report back on that when I can.

Cheers

**Comment by courville** [comment]
@WileyTheCoyote thx for the testing and initial feedback.

**Comment by piter-pit** [comment]
@courville I don't know what's the matter with my setup but unless I need to turn it on somehow I see no difference with previous versions. There is still erratic out of sync on regular video, on test video I see this silence...
Damn I really had a hope.
Of course AC3 recoding
@WileyTheCoyote did you test on AC3 recode or system encapsulation
Edit: ok, no passthrough

**Comment by WileyTheCoyote** [comment]
@piter-pit @courville 

AC3 (Universal) passthrough appeared to have a slight loss of sync, but I have not tested it further. System worked perfectly as did Nova.  Also as did no passthrough.

My setup (Google TV Streamer 4k), does not passthrough. It´s not an option in Setup. Rather it outputs PCM Multichannel or a specific Dolby format.

So for AC3 reencoding, one may ask why to use that if the source device has already encoded the stream.

Cheers

**Comment by WileyTheCoyote** [comment]
@courville 

Did some more tests on pause/resume, it looks great, no problems.  Tested with/without passthrough, with/without subtitles. Very long pause (30 minutes).

Also, Universal passthrough seems fine as well.

Cheers

**Comment by esnnn** [comment]
Update to .38 over .37 already installed.

**Without TV reboot**
- only AC3 recoding works 
- system encapsulation don't works (no sound)
- skip for a few seconds works ok
- lip sync looks a bit better now. 
- But it is freezing after pause/play completely. 

**After reboot** 
- system encapsulation begins to work ("stereo" output only). 
- Pause/resume works ok  
- Still DD only  of course, no DTS since the only method with recoding everything to DD is available. 

+ I have notice that Nova is the only player that definitely needs TV restart after update on my setup. (Android 12, sony kd-55x81j)

**Comment by piter-pit** [comment]
@esnnn I checked after TV full restart and for me the result is the same.

`So for AC3 reencoding, one may ask why to use that if the source device has already encoded the stream.`

@WileyTheCoyote it's useful then your AVR does not support certain audio coding, like mine does not support 5.1 AAC so nova can recode it to 5.1 AC3 which is supported by AVR - otherwise you have only stereo as fallback

**Comment by WileyTheCoyote** [comment]
@piter-pit it´s not my AVR, (which is a newer model and supports ¨all¨ formats) it´s the Google Streamer device that does not do passthrough.  It encodes. I´m not sure the significance of that, whether it impacts Nova or not.

Nova runs on my Google Streamer. The output from there is directly to the AVR via HDMI. Video from the AVR goes to the TV, audio goes to the 5.1 speakers.

Nova 6.4.38 is working on this setup.  I´ve tried several things to ¨break it¨, but it´s working, with or without Audio Passthrough. Nova. 6.4.37 only worked for me with Passthrough disabled and Dynamic Estimation ON.

Cheers.

**Comment by courville** [comment]
Some comments worth considering that could explain behavioral discrepencies:
* google streamer 4k can decide to reencode or not respect edid AVR capabilities: e.g. it never outputs truehd on mine while it works with nvidia shield
* ARC/eARC setups (TV set under Android OS connected to AVR) for ac3 recode is using android encapsulation passthrough since nova (IEC) encapsulations is not available which is not the default for direct HDMI connectivity to TV
* nova IEC encapsulation based passthrough avoids some Android/vendor system encapsulation behvior

**Comment by Macusercom** [comment]
Sony Bravia A90J (Android 12) using HDMI eARC with a Samsung Q990B Soundbar with Nova Player v6.4.38:

System Encapsulation works but audio seems 30-50 ms delayed (I'm very picky about that, others like my wife has not noticed it) but stays constant. If I change the audio delay to something else than 0 ms the video will freeze until it is set to 0 ms again.

AC3 re-encoding: it is offset by -300 ms (but constant at least). Settings an offset works here but the framerate drops to like half.

What does work now is scrubbing through a file while in previous version it seems the delay changed depending on what you do.

**Comment by courville** [comment]
I have found one passthrough mode 1 regression that should be fixed and I will address soon the manual delay regressions.

**Comment by piter-pit** [comment]
new version .39 did not help for me :(

**Comment by courville** [comment]
> new version .39 did not help for me :(

What part is still nok? Sound cuts in ac3 recode? Desync with which audio codec and passthrough mode? Can you please elaborate a little more?

**Comment by piter-pit** [comment]
Hi @courville I'm still experiencing audio/video out of sync in ac3 recoding. Tested on both eac3 and AAC 5.1 audio input. Delay is inconsistent eg once set to -360ms and in sync, when video closed and opened again it is no longer in sync with 360ms delay.
I understand it looks as an edge case as changes in the audio pipeline restructure didn't help

**Comment by courville** [comment]
> Hi [@courville](https://github.com/courville) I'm still experiencing audio/video out of sync in ac3 recoding. Tested on both eac3 and AAC 5.1 audio input. Delay is inconsistent eg once set to -360ms and in sync, when video closed and opened again it is no longer in sync with 360ms delay. I understand it looks as an edge case as changes in the audio pipeline restructure didn't help

This is not an edge case, your configuration is a bit out of mainstream because you have an tv under android os using earc with avr that uses in this case passthrough android encapsulation combined with ac3 recoding which is not the case with an android tv box plugged on avr linked to tv.

I have forced this mode and I can reproduce the delay.

**Comment by esnnn** [comment]
.39 is pretty mush the same as .38. 
- still need to restart the tv before it get to work "better"
- same situation with passthrough and sync
TV on A12, avr without earc/arc, optical SPDIF
I can try with different settings in case it will be interesting

**Comment by courville** [comment]
@piter-pit, please give another try with 6.4.40 regarding ac3 recode passthrough. I fixed a couple of issues related to the underlying passthrough android encapsulation that is used in your case compared to IEC encapsulation which is not possible in your eARC case.

**Comment by Macusercom** [comment]
I have tested 6.4.40 on my setup now: AC3 encapsulation works with a static -300 ms offset (although play/pause freezes, but restarting the video works flawlessly). System encapsulation with Dolby Atmos seems like -150 ms (but there is no way to correct with a positive offset). Audio ist slightly too early all the time.

**Comment by courville** [comment]
@Macusercom thanks for the feedback. I finally got a TV uder android tv and an AVR receiver and can reproduce on my side (I do not have such a setup at home).

**Comment by piter-pit** [comment]
Hi @courville I just tested .40 on AC3 recoding and on video with EAC3 sound I had to set audio delay by about minus 40-70ms (as someone mentioned positive delay is not possible to set? It was, I think)
On different EAC3 file it's similar.
On AAC 5.1 it's again around that minus 50ms so I would say it is consistent for all videos.
At last, just to have reference, I checked that bouncing ball test video and it was like minus 250ms and every 4rd bump was silent at for all all other versions, but again regular video are working consistently with ~ -50ms delay
Do you see similar behavior on your setup with test video?

**Comment by piter-pit** [comment]
Hi @courville should we close this topic? or you still plan to implement some changes? From my point, it works ok on regular video files with -40ms delay, and with test video issue I can live with that :)

**Comment by courville** [comment]
> Hi [@courville](https://github.com/courville) should we close this topic? or you still plan to implement some changes? From my point, it works ok on regular video files with -40ms delay, and with test video issue I can live with that :)

I would very much want to close the topic. Just test the new version where I changed everything again and reintroduced android frame synchronization and also managed to adopt a refined capacity based delay estimator tackling compressed packets for audio passthrough.

**Comment by piter-pit** [comment]
@courville you mean .41 it's the same, with -40ms delay is ok, however test video still mutes itself for a moment

**Comment by piter-pit** [comment]
Hi @courville,
I think I might be on to something with this case that on test video, with bouncing ball, that every 3rd bounce it was muted.
I recently received update on my TV, after that any communication with AVR was lost, couldn't receive sound nor display menu from AVR on tv - so any HDMI communication. But in HDMI new option appeared - option to disable eARC (so I believe I left with regular ARC only). Now it works, and even bouncing ball is not muted anymore every that 3rd bounce. Although I'm still not sure why it happened on old firmware while on old firmware and different video player it was ok but now it's ok... However I wonder if back then my tv was indeed eARC compatible or all the time worked as ARC?
Back then nova reported DTS_HD does it mean it was eARC?

<img width="2592" height="4608" alt="Image" src="https://github.com/user-attachments/assets/ea1c7ac5-76e3-4175-9584-86b0464daff5" />

<img width="2080" height="4608" alt="Image" src="https://github.com/user-attachments/assets/a3436e74-7478-4b2f-80ec-dac13cd3e525" />

**Comment by piter-pit** [comment]
Hi @courville I recently tested on video with EAC3+Atmos audio and there was out of sync, that -40ms was not correct. Can you please check?

**Comment by courville** [comment]
@piter-pit can you pelase get me `adb logcat` logs from a 10s playback (with lots of `avos_player` lines) using this [arm64 apk](https://drive.google.com/open?id=1KBvzLYc4vRl_LXIJNyklWHK0J_-12std) or [arm32 apk](https://drive.google.com/open?id=12IDp7H87GY7aFOSHGfc26NZWejQuHZZw) depending of your architecture

**Comment by piter-pit** [comment]
Hi @courville, this is strange - as I wrote I had an issue with eARC connection after update. After contact with TCL support I checked some settings and it helped to recover eARC - now when I played it is in sync. I believe it still might be an issue when play EAC3+Atmos -> AAC recode -> ARC (not eARC), let me know if you still wants a logs or not - I can try to reproduce this

**Comment by courville** [comment]
Trying to summarize the current situation to check if I am getting it right. My understanding is that playback is now in sync when the TV-to-AVR connection operates in eARC mode. The remaining issue may only affect EAC3+Atmos converted to AC3 while the connection falls back to regular ARC.  Is that correct, and can you reproduce it consistently in that exact configuration?
If you can, then I am interested to get the logs.

**Comment by piter-pit** [comment]
Hi @courville yes, that was my observation, however now, when I tried to reproduce it seems ok-ish at least with only eARC -> ARC change. let me check firmly during the weekend I will try to revert all android settings

**Comment by piter-pit** [comment]
Hi @courville so I've made some more tests:
It doesn't seem that ARC mode was a problem as I initially though, I switched between eARC and ARC and between direct access and auto as it was set initially and deny eARC mode, nevertheless there is something with EAC3+Atmos sound synchronization but it's not consistent.
When I played initially file 1 I couldn't sync it with audio -> delay option, however as I played it second time it was ok (that's why I connected it to eARC/ARC mode that I changed just a moment ago), however 2 days ago I revert to ARC mode and played and it was ok, so I got back to eARC and yesturday played different file with EAC3+Atmos and it was off, played it today and I've noticed that initially it was ok then moved a little out of sync - maybe that was a case. In addition I disabled AC3 recoding in nova and set system encapsulation and since by AVR is capable of decoding it it was in sync, same situation on different player but it wasn't recoding since it was capable codec
Please have a look on two logs, one is from file 1 from 2 days ago and one is from today on file 2 with slightly longer play with changing delay during playback.

Please let me know if you see something, or maybe you can consider selective recoding only for not supported formats?

**Comment by courville** [comment]
I think your logs reveal an issue in Nova’s latency model. On your setup, AC3 recoding uses Android system encapsulation rather than Nova’s IEC encapsulation, but Nova was not applying its measured AudioTrack occupancy correction to that path. AC3 recoding using system encapsulation should use the same trusted occupancy model as other Mode 2 output, and this is now being corrected.

**Comment by piter-pit** [comment]
Great, I mean great that you were able to fix it that quickly and that out of sync was not just my imagination 😂

**Comment by courville** [comment]
I hope the changes I made will address your issue.
Can you please try this [arm64 apk](https://drive.google.com/open?id=1i8oWaWMbxIYYTQTXFL6j2Vbkq7jEqxTP) or [arm32 apk](https://drive.google.com/open?id=1KVLNY-1xaZR8O-QjIKAj7p9lQP5x6bEg) depending of your architecture and report if it helps?
These apks contains extra logging capabilities in case we need to investigate further.

**Comment by piter-pit** [comment]
Hi @courville it looks good, thanks! 🙂
